(library
 (name hps_equivalence)
 (modules hps_equivalence)
 (libraries hqbricks zarith))

(executable
 (name hqbricks_eq)
 (modules hqbricks_eq)
 (libraries cmdliner hps_equivalence))

(test
 (name equivalence_test)
 (modules equivalence_test)
 (libraries alcotest hps_equivalence hqbricks zarith))
